In [1]:
import pandas as pd

In [2]:
sub1 = pd.read_csv('./nb_svm_sklearny_submission.csv')
sub2 = pd.read_csv('./nb_svm_strong_linear_baseline_submission.csv')

In [3]:
sub1.head()

,id,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,00001cee341fdb12,0.999988,0.106262,0.999987,0.002370,0.962578,0.094959
1,0000247867823ef7,0.002873,0.000604,0.001893,0.000100,0.002227,0.000342
2,00013b17ad220c46,0.011755,0.000864,0.005588,0.000102,0.003210,0.000297
3,00017563c3f7919a,0.000960,0.000224,0.001141,0.000171,0.001057,0.000297
4,00017695ad8997eb,0.009957,0.000485,0.002009,0.000131,0.002395,0.000351

In [4]:
sub2.head()

,id,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,00001cee341fdb12,0.999988,0.106265,0.999987,0.002369,0.962578,0.094955
1,0000247867823ef7,0.002873,0.000604,0.001893,0.000100,0.002227,0.000342
2,00013b17ad220c46,0.011755,0.000864,0.005588,0.000102,0.003210,0.000297
3,00017563c3f7919a,0.000960,0.000224,0.001141,0.000171,0.001057,0.000297
4,00017695ad8997eb,0.009957,0.000485,0.002009,0.000131,0.002395,0.000351

In [5]:
sub1.equals(sub2)

False

In [6]:
merged = pd.merge(sub1, sub2, on='id')
merged.shape

(153164, 13)

In [7]:
merged.head(10)

,id,toxic_x,severe_toxic_x,obscene_x,threat_x,insult_x,identity_hate_x,toxic_y,severe_toxic_y,obscene_y,threat_y,insult_y,identity_hate_y
0,00001cee341fdb12,0.999988,0.106262,0.999987,0.002370,0.962578,0.094959,0.999988,0.106265,0.999987,0.002369,0.962578,0.094955
1,0000247867823ef7,0.002873,0.000604,0.001893,0.000100,0.002227,0.000342,0.002873,0.000604,0.001893,0.000100,0.002227,0.000342
2,00013b17ad220c46,0.011755,0.000864,0.005588,0.000102,0.003210,0.000297,0.011755,0.000864,0.005588,0.000102,0.003210,0.000297
3,00017563c3f7919a,0.000960,0.000224,0.001141,0.000171,0.001057,0.000297,0.000960,0.000224,0.001141,0.000171,0.001057,0.000297
4,00017695ad8997eb,0.009957,0.000485,0.002009,0.000131,0.002395,0.000351,0.009957,0.000485,0.002009,0.000131,0.002395,0.000351
5,0001ea8717f6de06,0.004428,0.000280,0.001964,0.000373,0.003182,0.000364,0.004428,0.000280,0.001964,0.000373,0.003182,0.000364
6,00024115d4cbde0f,0.000535,0.000156,0.000825,0.000102,0.000704,0.000411,0.000535,0.000156,0.000825,0.000102,0.000704,0.000411
7,000247e83dcc1211,0.187793,0.000366,0.003324,0.000132,0.007759,0.000342,0.187793,0.000366,0.003324,0.000132,0.007759,0.000342
8,00025358d4737918,0.009363,0.000135,0.002518,0.000095,0.003299,0.000394,0.009363,0.000135,0.002518,0.000095,0.003299,0.000394
9,00026d1092fe71cc,0.003037,0.000229,0.002203,0.000110,0.002957,0.000276,0.003037,0.000229,0.002203,0.000110,0.002957,0.000276

In [8]:
label_cols = ['toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate']

for label in label_cols: 
    comp = merged[[label + '_x', label + '_y']]
    ssd = ((comp.iloc[:, 0] - comp.iloc[:, 1])**2).sum()
    print('{} sum square difference: {}'.format(label, ssd))

toxic sum square difference: 1.175567587454938e-10
severe_toxic sum square difference: 1.704488143352003e-06
obscene sum square difference: 2.8716107011098387e-07
threat sum square difference: 3.5540359343794753e-06
insult sum square difference: 2.4807481083432632e-08
identity_hate sum square difference: 1.461866057562123e-06